---

- hosts: localhost
  become: true
  roles: 
    - install
      tags: install
    - flatpak
      tags: flatpak
    - git-setup
      tags: git
    - vim
      tags: vim
    - tmp2tmpfs
      tags: tmp2tmpfs
    - zsh
      tags: zsh
