---

- name: Install Software
  import_tasks: software_install.yml
  
- name: Marble Mouse setup
  import_tasks: marble_mouse.yml

- name: Git setup
  import_tasks: git_setup.yml
  
- name: Set up /tmp to tmpfs
  import_tasks: tmp2tmpfs.yml
