---

- name: Install Software
  import_tasks: software_install.yml
  
- name: Marble Mouse setup
  import_tasks: marble_mouse.yml

- name: Git setup
  import_tasks: git_setup.yml
  
- name: Vim setup
  import_tasks: vim_setup.yml
  
- name: Set up /tmp to tmpfs
  import_tasks: tmp2tmpfs.yml
  
- name: Performe set up and fine tuning of ZSH
  import_tasks: zsh_fine_tuning.yml

- name: Perform install via snap on Ubuntu
  import_tasks: snap_install.yml
  tags:
    - snap
