---

- name: Install Software
  apt: 
    pkg: "{{ utils + \
             text_editors + \
             development + \
             internet + \
             graphic + \
             photo + \
             video + \
             music + \
             games }}"
    state: latest
    update_cache: true
    autoclean: true
    autoremove: false
